---
include:
  - project: nci-gdc/gitlab-templates
    ref: feat/components
    file:
      - templates/artifacts/python-service.yaml

variables:
  LANGUAGE_VERSION: python3.13
  BASE_CONTAINER_VERSION: 4

tox:
  extends: .tox
  services:
    - name: docker.osdc.io/ncigdc/ci-elasticsearch-7:${BASE_CONTAINER_VERSION}
      alias: elasticsearch
      variables:
        ES_JAVA_OPTS: -Xms2g -Xmx2g
  variables:
    BOTO_CONFIG: /dev/null
    ES_NODES: http://elasticsearch:9200
  script:
    - !reference [.tox, script]
    - (apt-get update -y) || (dnf update -y)
    - (apt-get install -y maven) || (dnf install -y maven)
    - java -version
    - mvn -version
    - uv tool run tox -e test
    - uv tool run tox -e coverage

.deploy-service-with-salt:
  before_script:
    - export DEPLOY_SERVICE_TAG=${CI_COMMIT_TAG:-$CI_COMMIT_SHA}

.services:
  allow_failure: true
  stage: deploy
  when: manual
  parallel:
    matrix:
      - DEPLOY_SERVICE_LIST: [mutation_indexer]
