---
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/artifacts/python-docker-service.yaml

variables:
  BASE_CONTAINER_VERSION: 3.5.0
  LANGUAGE_VERSION: python3.13
  SERVICE_NAME: mutation_indexer
  UV_INDEX: https://nexus.osdc.io/repository/pypi-gdc-releases/simple

tox:
  services:
    - name: docker.osdc.io/ncigdc/ci-elasticsearch-7:${BASE_CONTAINER_VERSION}
      alias: elasticsearch
      variables:
        ES_JAVA_OPTS: -Xms2g -Xmx2g
  variables:
    BOTO_CONFIG: /dev/null
    ES_NODES: http://elasticsearch:9200
  before_script:
    - (apt-get update -y) || (dnf update -y)
    - (apt-get install -y maven) || (dnf install -y maven)
    - java -version
    - mvn -version
    - curl -LsSf https://astral.sh/uv/install.sh | sh
  script:
    - uvx --with tox-uv tox r


.deploy-service-with-salt:
  before_script:
    - export DEPLOY_SERVICE_TAG=${CI_COMMIT_TAG:-$CI_COMMIT_SHA}

.services:
  allow_failure: true
  stage: deploy
  when: manual
  parallel:
    matrix:
      - DEPLOY_SERVICE_LIST: [mutation_indexer]
