dist: xenial

language: python

python:
  - "2.7"

jdk:
  - openjdk8

addons:
  apt:
    packages:
      - libyaml-dev

cache: pip

env:
  global:
    - SPARK_VERSION="2.0.1"
    - ES_VERSION="5.4.3"
    - BOTO_CONFIG=/dev/null

before_install:
  - wget http://d3kbcqa49mib13.cloudfront.net/spark-${SPARK_VERSION}-bin-hadoop2.7.tgz;
  - wget http://download.elastic.co/hadoop/elasticsearch-hadoop-${ES_VERSION}.zip
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.deb && sudo dpkg --force-confnew -i elasticsearch-${ES_VERSION}.deb
  - sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install mapper-size
  - sudo fallocate -l 5G /mnt/swap.file
  - sudo mkswap /mnt/swap.file
  - sudo swapon /mnt/swap.file
  - sudo sed -i 's/^-Xms.*/-Xms2g/' /etc/elasticsearch/jvm.options
  - sudo sed -i 's/^-Xmx.*/-Xmx2g/' /etc/elasticsearch/jvm.options
  - sudo service elasticsearch restart

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - python setup.py install 
  - tar -xzvf spark-${SPARK_VERSION}-bin-hadoop2.7.tgz
  - unzip elasticsearch-hadoop-${ES_VERSION}.zip
  - export SPARK_HOME=`pwd`/spark-${SPARK_VERSION}-bin-hadoop2.7;
  - export PYTHONPATH=$SPARK_HOME/python/:$PYTHONPATH
  - export PYTHONPATH=$SPARK_HOME/python/lib/py4j-0.10.3-src.zip:$PYTHONPATH
  - cp `pwd`/elasticsearch-hadoop-${ES_VERSION}/dist/elasticsearch-spark-20_2.11-${ES_VERSION}.jar $SPARK_HOME/jars

script:
  - java -version
  - curl http://localhost:9200/
  - sudo cat /etc/elasticsearch/jvm.options
  - "py.test tests -vvv -m 'not do_not_collect'"  # this will not show tests that are marked "do_not_collect" in pytest output
