dist: xenial

language: python

python:
  - "3.6"

jdk:
  - openjdk8

addons:
  apt:
    packages:
      - libyaml-dev

cache: pip

env:
  global:
    - SPARK_VERSION="2.4.5"
    - ES_VERSION="7.16.3"
    - BOTO_CONFIG=/dev/null

before_install:
  # Work around a bug in the Travis Xenial image where the environment is
  # always configured for OpenJDK 11 unless you set language: java.
  # The official Spark builds are compiled on Java 8.
  - export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
  - export PATH="${JAVA_HOME}/bin:${PATH}"
  - wget https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop2.7.tgz
  - wget https://artifacts.elastic.co/downloads/elasticsearch-hadoop/elasticsearch-hadoop-${ES_VERSION}.zip
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}-amd64.deb && sudo dpkg --force-confnew -i elasticsearch-${ES_VERSION}-amd64.deb
  - sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install mapper-size
  - sudo fallocate -l 5G /mnt/swap.file
  - sudo mkswap /mnt/swap.file
  - sudo swapon /mnt/swap.file
  - sudo sed -i 's/^-Xms.*/-Xms2g/' /etc/elasticsearch/jvm.options
  - sudo sed -i 's/^-Xmx.*/-Xmx2g/' /etc/elasticsearch/jvm.options
  - sudo chown elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch restart

install:
  - tar -xzvf spark-${SPARK_VERSION}-bin-hadoop2.7.tgz
  - unzip elasticsearch-hadoop-${ES_VERSION}.zip
  - export SPARK_HOME=`pwd`/spark-${SPARK_VERSION}-bin-hadoop2.7;
  - cp `pwd`/elasticsearch-hadoop-${ES_VERSION}/dist/elasticsearch-spark-20_2.11-${ES_VERSION}.jar $SPARK_HOME/jars
  - pip install tox-travis

script:
  - java -version
  - curl http://localhost:9200/
  - sudo cat /etc/elasticsearch/jvm.options
  - tox
