dist: xenial

language: python

python:
  - "3.5"

services:
  - docker

jdk:
  - openjdk8

addons:
  apt:
    sources:
      - docker-xenial
    packages:
      - libyaml-dev
      - docker-ce

cache: pip

env:
  global:
    - SPARK_VERSION="2.4.5"
    - ES_VERSION="7.6.2"
    - BOTO_CONFIG=/dev/null
    - secure: T9A6zulsRH0YUQBzGy0jFQaoHmpnIefrVUkHYogtFIctNSML+tEhaMzTOy3PKesNdB2uI4AUcccyy4sIuWjSB47uW3rx8KH7HRqFOQa1Bm7f4hqH7sttuypOUugfmloH45IWLLDsy91xfWcwy66eB59S5BIh3Jx/ntze74vQgWIjjhTxXTnt9Lke3nit0lVMMv2LwYLH80hQvpmmisriPSd0yR1NLijwAaT2OJ6kG0NFmDApb9hyvg6FXtTPFYXBPIheaiZ9Tttl6rrD48sRm7TGOegyo6CZPgq2A0Atjp66FnYPFkT//uxU3iN3m2uipWU0/vfRIZhSd1i5pI1+N6kEHedM8+048dwc++j+lbOyfCtqbngq6toXLpMcz+lOcpgs4HzW277dMiMFi+6PVmwXGCEca7Gkno3fvRFc13WTMLgE7Tp2gviNYsb9tQFiTBXmiMHSt46FhT28dmGbbqzG3cK5WtfksFLEGvFAduMxGA9/6i6ja+TZe7Yx0RR8gdoj2/SFPRhRg2NOjEAuYLzjeN8ysk+Hx4ijjrhhA5C9gJ4iZcuC/c/rKewL9Kf+xDJVnZk54oPtXlz4KqBkJggBLB6qeWn0KXylct6htczo15ADkKO629JvatKr6OdEJBWTiYi1lV/9HPLje2Ws3p+I3YSkVdcJcGMZVwgmK4s=  # pragma: allowlist secret
    - secure: RIX9tMNpEm8HTd3mLoww0ACdTPoKG59xVKRot3cMexkt07xFlN5ZJAJCzk6n7PFQCzUAkRbfsU30yL6iecu/YffVWwTVURFfrrhBNgJZFuAYpBvk2fTzxSz6jd8x+qkK4U7BTFdnPI0yb6zEWsZuRGzM4rwZ1r2FjtfLSUtiCfMDza4XsvgxnI7+rnwiKe03g4Q4tR5WSfq2haFir1a3iFn+66Da30Cg451jlm5ajBShtvEZM55jvlT5UfMCQuWxYG8Aonc+X4bYCHaCpVzqrhwYjcJZOQeyZM0IcDtsh+hrpbsrF45ZvaavpLyaP6dVR9gYOQQM/yNKeFlYNRPBAtqf7d5fTmls0OUacQup352lcmRhpoO5ii8KzVOyeaQ8pkhZGJvbFaMqNDABo37AUt6iS+10sZS2nJhnC0/LcUM0pbE/g34CuQ3P5gOfRrWzAdlGR4NSpQozEsNPVtFPSdZK05ELnlWkmvh8ZRhzdEG+yy5s91iiEo9SmJTmEQi9SvMmYVRjXoMmEnBcziJejtmBNIPHBVAtkzbsSGyMzb6MRQWAT3KrajGjzwQ5b6mC+RNY8pQzCEwR9bvVpHzdoTRJWORi7YfK/ZcDzo7grz+m854TPuBZ1WegAMOHMIFkMUjgr4fTLyLTz33533q86CIrroUZVyZRQGXSHj9MKHI=  # pragma: allowlist secret

before_install:
  # Work around a bug in the Travis Xenial image where the environment is
  # always configured for OpenJDK 11 unless you set language: java.
  # The official Spark builds are compiled on Java 8.
  - docker --version
  - export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
  - export PATH="${JAVA_HOME}/bin:${PATH}"
  - wget https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop2.7.tgz
  - wget https://artifacts.elastic.co/downloads/elasticsearch-hadoop/elasticsearch-hadoop-${ES_VERSION}.zip
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}-amd64.deb && sudo dpkg --force-confnew -i elasticsearch-${ES_VERSION}-amd64.deb
  - sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install mapper-size
  - sudo fallocate -l 5G /mnt/swap.file
  - sudo mkswap /mnt/swap.file
  - sudo swapon /mnt/swap.file
  - sudo sed -i 's/^-Xms.*/-Xms2g/' /etc/elasticsearch/jvm.options
  - sudo sed -i 's/^-Xmx.*/-Xmx2g/' /etc/elasticsearch/jvm.options
  - sudo chown elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch restart

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - python setup.py install
  - tar -xzvf spark-${SPARK_VERSION}-bin-hadoop2.7.tgz
  - unzip elasticsearch-hadoop-${ES_VERSION}.zip
  - export SPARK_HOME=`pwd`/spark-${SPARK_VERSION}-bin-hadoop2.7;
  - export PYTHONPATH=$SPARK_HOME/python/:$PYTHONPATH
  - export PYTHONPATH=$SPARK_HOME/python/lib/py4j-0.10.7-src.zip:$PYTHONPATH
  - cp `pwd`/elasticsearch-hadoop-${ES_VERSION}/dist/elasticsearch-spark-20_2.11-${ES_VERSION}.jar $SPARK_HOME/jars

script:
  - java -version
  - curl http://localhost:9200/
  - sudo cat /etc/elasticsearch/jvm.options
  - "py.test tests -vvv -m 'not do_not_collect'"  # this will not show tests that are marked "do_not_collect" in pytest output

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash -e docker/docker_deploy.sh; fi
