[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=68", "wheel", "setuptools_scm[toml]>=7.0", "versionista>=1.1.0"]

[project]
authors = [{name = "NCI GDC", email = "support@nci-gdc.datacommons.io"}]
classifiers = [
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python"
]
dependencies = [
  "boto3",
  "boto3-stubs[s3]",
  "deepmerge",
  "elasticsearch[async]~=7.0",
  "importlib-resources",
  "marshmallow-dataclass",
  "marshmallow-enum",
  "more-itertools",
  "numpy",
  "pyspark",
  "python-json-logger",
  "pyyaml~=6.0",
  "toml",
  "typing-extensions",
  "indexclient",
  "gdcmodels",
  "mutation-indexer-resource @ git+ssh://git@github.com/NCI-GDC/mutation-indexer-resource.git@1.0.0"
]
description = "ETL for mutation elasticsearch indices"
dynamic = ["version"]
license = {file = "LICENSE"}
name = "gdc-mutation-indexer"
requires-python = "~=3.9"

[project.optional-dependencies]
client = ["halo", "pex", "wheel"]
dev = ["click~=8.1", "coverage[toml]~=7.0", "deepdiff~=6.0", "pytest~=8.0"]

[project.scripts]
mutation-indexer = "mutation_indexer.client:main [client]"

[project.urls]
repository = "https://github.com/NCI-GDC/gdc-mutation-indexer"

[tool.coverage.html]
directory = "docs/htmlcov"
title = "mutation-indexer coverage report"

[tool.coverage.run]
branch = true
source = ["mutation_indexer"]

[tool.isort]
known_first_party = ["mutation_indexer"]
multi_line_output = 3
profile = "black"

[tool.mypy]
plugins = ["marshmallow_dataclass.mypy"]

[tool.pytest.ini_options]
addopts = "-rflv"
markers = [
  "do_not_collect",
  "gistic_build",
  "ssm_occurrence_centric_ssm_subtree",
  "gistic_combine",
  "gene_centric_ssm_subtree",
  "cnv_occurrence_centric_cnv_subtree",
  "case_centric_ssm_subtree"
]
minversion = "6.0"
testpaths = ["tests/unit", "tests/integration"]

[tool.setuptools_scm]
local_scheme = "versionista-local-format"
version_scheme = "versionista-format"

[tool.tox]
requires = ["tox>=4.21"]

[tool.tox.env.coverage]
commands = [["coverage", "html"], ["coverage", "xml"]]
deps = ["-crequirements.txt", "coverage[toml]"]
skip_install = true

[tool.tox.env.pex]
base_python = ["py313"]
commands = [
  [
    "pex",
    ".[client]",
    "--python=python{env:SCIE_PYTHON_VERSION}",
    "--entry-point=mutation_indexer.client",
    "--constraints=requirements.txt",
    "--output-file=mutation-indexer",
    "--runtime-pex-root={env:RUNTIME_PEX_ROOT}",
    "--scie=eager",
    "--scie-platform={env:SCIE_PLATFORM}",
    "--scie-python-version={env:SCIE_PYTHON_VERSION}"
  ],
  [
    "pex",
    ".",
    "--python=python{env:SCIE_PYTHON_VERSION}",
    "--constraints=requirements.txt",
    "--output-file=driver-all",
    "--runtime-pex-root={env:RUNTIME_PEX_ROOT}",
    "--scie=eager",
    "--scie-platform={env:SCIE_PLATFORM}",
    "--scie-python-version={env:SCIE_PYTHON_VERSION}"
  ]
]
deps = ["-crequirements.txt", "pex"]
pass_env = ["SSH_AUTH_SOCK"]
skip_install = true

[tool.tox.env.pex.set_env]
RUNTIME_PEX_ROOT = {replace = "env", name = "RUNTIME_PEX_ROOT", default = "/tmp"}
SCIE_PLATFORM = {replace = "env", name = "SCIE_PLATFORM", default = "linux-x86_64"}
SCIE_PYTHON_VERSION = {replace = "env", name = "SCIE_PYTHON_VERSION", default = "3.9"}

[tool.tox.env.publish]
commands = [
  [
    "python",
    "-m",
    "setuptools_scm"
  ],
  [
    "python",
    "-m",
    "build"
  ],
  [
    "python",
    "-m",
    "twine",
    "check",
    "dist/*"
  ],
  [
    "python",
    "-m",
    "twine",
    "upload",
    "dist/*"
  ]
]
deps = ["setuptools_scm", "build", "twine"]
pass_env = ["TWINE_*"]
skip_install = true

[tool.tox.env.test]
allowlist_externals = ["bin/spark-install.sh"]
commands = [
  [
    "coverage",
    "run",
    "-m",
    "pytest",
    "-vv",
    {replace = "posargs", default = [
      "-m",
      "not do_not_collect",
      "--junitxml=report.xml"
    ], extend = true}
  ],
  [
    "coverage",
    "report"
  ]
]
commands_pre = [["bin/spark-install.sh"]]
deps = ["-crequirements.txt", ".[dev,client]"]
pass_env = ["BOTO_CONFIG", "ES_*", "JAVA_HOME", "SPARK_HOME", "SSH_AUTH_SOCK"]

[tool.tox.env.test.set_env]
NO_PROXY = "localhost,postgres,127.0.0.1,::1,elasticsearch"
PIP_INDEX_URL = "https://nexus.osdc.io/repository/pypi-gdc-releases/simple"
no_proxy = "localhost,postgres,127.0.0.1,::1,elasticsearch"

[tool.tox.env_run_base]
base_python = ["py39"]
