[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=80", "setuptools-scm"]

[dependency-groups]
dev = ["click", "coverage", "deepdiff", "inflect", "jinja2", "pytest"]

[project]
authors = [{name = "NCI GDC", email = "support@nci-gdc.datacommons.io"}]
classifiers = [
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python"
]
dependencies = [
  "deepmerge",
  "importlib-resources",
  "marshmallow~=3.0",
  "marshmallow-dataclass",
  "more-itertools",
  "pyspark~=3.5.0",
  "python-json-logger",
  "tomli",
  "tomli-w",
  "typing-extensions"
]
description = "ETL for mutation elasticsearch indices"
dynamic = ["version"]
license = {file = "LICENSE"}
name = "gdc-mutation-indexer"
requires-python = "~=3.13.0"

[project.optional-dependencies]
client = [
  "elasticsearch[async]",
  "halo",
  "typed-argument-parser"
]
gene-expression = [
  "boto3",
  "boto3-stubs[s3]",
  "elasticsearch",
  "gdcmodels>=5.10",
  "indexclient<3",
  "numpy",
  "mutation-indexer-resource"
]
viz = [
  "elasticsearch",
  "gdcmodels>=5.10",
  "indexclient<3",
  "mutation-indexer-resource"
]

[project.scripts]
mutation-indexer = "mutation_indexer.client:main"
driver-gene-expression = "mutation_indexer.gene_expression.driver:main"
driver-viz = "mutation_indexer.viz.driver:main"

[project.urls]
repository = "https://github.com/NCI-GDC/gdc-mutation-indexer"

[tool.coverage.html]
directory = "docs/htmlcov"
title = "mutation-indexer coverage report"

[tool.coverage.run]
branch = true
source = ["mutation_indexer"]

[tool.mypy]
plugins = ["marshmallow_dataclass.mypy"]

[tool.pytest.ini_options]
addopts = "-rflv"
markers = [
  "ssm_occurrence_centric_ssm_subtree",
  "gene_centric_ssm_subtree",
  "cnv_occurrence_centric_cnv_subtree",
  "case_centric_ssm_subtree",
  "case_schema_dependent: Marks a test which is dependent on an input case schema."
]
minversion = "6.0"
testpaths = ["tests/unit", "tests/integration"]

[tool.ruff]
line-length = 95
src = ["src", "tests"]
target-version = "py313"

[tool.ruff.lint]
# see https://docs.astral.sh/ruff/rules/
select = [
  "E", # pydocstyle errors
  "F", # pyflakes
  "I", # isort
  "N", # pep8 naming
  "RUF", # ruff specific rules
  "UP", # pyupgrade
  "W" # pydocstyle warnings
]
ignore = [
  "E501",
  "N815"
]

[tool.ruff.lint.flake8-import-conventions.aliases]
"pyspark.sql.functions" = "F"

[tool.ruff.lint.isort]
known-first-party = ["mutation_indexer", "tests"]

[tool.ruff.lint.pep8-naming]
extend-ignore-names = ["F"]

[tool.ruff.lint.pyupgrade]
keep-runtime-typing = true

[tool.setuptools_scm]
fallback_version = "0.0.0"

[tool.tox]
env_list = ["py313", "coverage"]

[tool.tox.env.coverage]
commands = [["coverage", "html"], ["coverage", "xml"]]
skip_install = true

[tool.tox.env_run_base]
allowlist_externals = ["bin/spark-install.sh"]
commands = [
  [
    "coverage",
    "run",
    "-m",
    "pytest",
    "-vv",
    {replace = "posargs", default = [
      "--junitxml=report.xml"
    ], extend = true}
  ],
  [
    "coverage",
    "report"
  ]
]
commands_pre = [["bin/spark-install.sh"]]
dependency_groups = ["dev"]
extras = ["client", "gene-expression", "viz"]
pass_env = [
  "BOTO_CONFIG",
  "ES_*",
  "JAVA_HOME",
  "SPARK_HOME",
  "SSH_AUTH_SOCK"
]
runner = "uv-venv-lock-runner"

[tool.tox.env_run_base.set_env]
NO_PROXY = "localhost,postgres,127.0.0.1,::1,elasticsearch"
no_proxy = "localhost,postgres,127.0.0.1,::1,elasticsearch"

[[tool.uv.index]]
name = "nexus"
url = "https://nexus.osdc.io/repository/pypi-all/simple"
