[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=68", "wheel", "setuptools_scm[toml]>=7.0", "versionista>=1.1.0"]

[dependency-groups]
dev = ["click", "coverage[toml]", "deepdiff", "inflect", "pytest"]

[project]
authors = [{name = "NCI GDC", email = "support@nci-gdc.datacommons.io"}]
classifiers = [
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python"
]
dependencies = [
  "deepmerge",
  "importlib-resources",
  "marshmallow~=3.0",
  "marshmallow-dataclass",
  "more-itertools",
  "pyspark~=3.5.0",
  "python-json-logger",
  "tomli",
  "tomli-w",
  "typed-argument-parser",
  "typing-extensions"
]
description = "ETL for mutation elasticsearch indices"
dynamic = ["version"]
license = {file = "LICENSE"}
name = "gdc-mutation-indexer"
requires-python = "~=3.13.0"

[project.optional-dependencies]
client = ["halo"]
gene-expression = [
  "boto3",
  "boto3-stubs[s3]",
  "elasticsearch[async]",
  "gdcmodels",
  "indexclient",
  "mutation-indexer-resource",
  "numpy"
]
viz = ["elasticsearch[async]", "gdcmodels", "indexclient", "mutation-indexer-resource"]

[project.scripts]
mutation-indexer = "mutation_indexer.client:main [client]"

[project.urls]
repository = "https://github.com/NCI-GDC/gdc-mutation-indexer"

[tool.coverage.html]
directory = "docs/htmlcov"
title = "mutation-indexer coverage report"

[tool.coverage.run]
branch = true
source = ["mutation_indexer"]

[tool.isort]
known_first_party = ["mutation_indexer"]
multi_line_output = 3
profile = "black"

[tool.mypy]
plugins = ["marshmallow_dataclass.mypy"]

[tool.pytest.ini_options]
addopts = "-rflv"
markers = [
  "ssm_occurrence_centric_ssm_subtree",
  "gene_centric_ssm_subtree",
  "cnv_occurrence_centric_cnv_subtree",
  "case_centric_ssm_subtree",
  "case_schema_dependent: Marks a test which is dependent on an input case schema."
]
minversion = "6.0"
testpaths = ["tests/unit", "tests/integration"]

[tool.ruff]
line-length = 95
src = ["src", "tests"]
target-version = "py313"

[tool.setuptools_scm]
local_scheme = "versionista-local-format"
version_scheme = "versionista-format"

[tool.tox]
requires = ["tox>=4.21"]

[tool.tox.env_run_base]
allowlist_externals = ["bin/spark-install.sh"]
base_python = ["py313"]
commands = [
  [
    "coverage",
    "run",
    "-m",
    "pytest",
    "-vv",
    {replace = "posargs", default = [
      "--junitxml=report.xml"
    ], extend = true}
  ],
  [
    "coverage",
    "report"
  ],
  [
    "coverage",
    "html"
  ],
  [
    "coverage",
    "xml"
  ]
]
commands_pre = [["bin/spark-install.sh"]]
dependency_groups = ["dev"]
extras = ["cliend", "gene-expression", "viz"]
pass_env = ["BOTO_CONFIG", "ES_*", "JAVA_HOME", "SPARK_HOME", "SSH_AUTH_SOCK"]

[tool.tox.env_run_base.set_env]
NO_PROXY = "localhost,postgres,127.0.0.1,::1,elasticsearch"
PIP_INDEX_URL = "https://nexus.osdc.io/repository/pypi-gdc-releases/simple"
no_proxy = "localhost,postgres,127.0.0.1,::1,elasticsearch"

[[tool.uv.index]]
name = "nexus"
url = "https://nexus.osdc.io/repository/pypi-gdc-releases/simple"
