[tox]
minversion = 3.4.0
envlist = py{39,310}
skip_missing_interpreters = true

[testenv]
passenv =
    BOTO_CONFIG
    ES_*
    JAVA_HOME
    SPARK_HOME
setenv =
    PIP_INDEX_URL=https://nexus.osdc.io/repository/pypi-all/simple
    ES_VERSION = {env:ES_VERSION:7.7.1}
    NO_PROXY=localhost,postgres,127.0.0.1,::1,elasticsearch
    no_proxy=localhost,postgres,127.0.0.1,::1,elasticsearch
deps =
    .[dev,client]
    -r requirements.txt
    -r client-requirements.txt
allowlist_externals =
    bash
commands_pre =
    bash ./bin/spark-install.sh
commands =
    pytest -vv {posargs: -m 'not do_not_collect' --cov=mutation_indexer --cov-report xml --cov-report term}

[testenv:publish]
passenv =
  TWINE_*
skip_install=true
deps =
    setuptools_scm
    build
    twine
install_command =
    python -m pip install {opts} {packages}
commands_pre =
commands =
    python -m setuptools_scm
    python -m build
    python -m twine check dist/*
    python -m twine upload dist/*
commands_post =
