[tox]
minversion = 3.4.0
envlist = py{36,37}
skip_missing_interpreters = true

[testenv]
passenv =
    BOTO_CONFIG
    ES_VERSION
    SPARK_HOME
setenv =
    ES_VERSION = {env:ES_VERSION:7.7.1}
usedevelop = true
deps =
    -rrequirements.txt
    -rdev-requirements.txt
    -rmaster-requirements.txt
install_command = python -m pip install --no-deps {opts} {packages}
allowlist_externals =
    bash
commands_pre =
    bash ./spark-install.sh
commands =
    pytest -vv {posargs: -m 'not do_not_collect' --cov=exports --cov-report xml --cov-report term}
