settings:
  index:
    refresh_interval: 1m
    number_of_shards: 16
    number_of_replicas: 0
    mapper.dynamic: False
    mapping.nested_fields.limit: 100
    mapping.total_fields.limit: 2000
  analysis:
    analyzer:
      id_index:
        filter:
          - lowercase
          - edge_ngram
        type: custom
        tokenizer: whitespace
      id_search:
        filter:
          - lowercase
        type: custom
        tokenizer: whitespace
mappings:
  build_metadata:
    properties:
      commit_hash:
        type: text
      number_of_mutations:
        type: double
      number_of_projects:
        type: double
      debug:
        type: text
      maf_urls:
        type: text
      percentile_threshold:
        properties:
          name:
            type: text
          value:
            type: double
      coalesce:
        type: double
      batch_size_bytes:
        type: text
      batch_size_entries:
        type: double
    _all:
      enabled: false
    _source:
      excludes: [__comment__]
    dynamic: strict
common_mapping_settings:
  _all:
    enabled: false
  _source:
    excludes: [__comment__]
  dynamic: true
