settings:
  index:
    refresh_interval: 1m
    number_of_shards: 16
    number_of_replicas: 1
    mapper.dynamic: False
    mapping.nested_fields.limit: 100
    mapping.total_fields.limit: 2000
  analysis:
    analyzer:
      id_index:
        filter:
          - lowercase
          - edge_ngram
        type: custom
        tokenizer: whitespace
      id_search:
        filter:
          - lowercase
        type: custom
        tokenizer: whitespace
mappings:
  _all:
    enabled: false
  _source:
    excludes: [__comment__]
  dynamic: true
  build_metadata:
    properties:
      commit_hash:
        type: text
        default: empty
      number_of_projects:
        type: double
        default: empty
      maf_urls:
        type: text
        default: empty
      percentile:
        properties:
          name:
            type: text
            default: empty
          value:
            type: double
            default: empty
      coalesce:
        type: double
        default: empty
      batch_size_bytes:
        type: text
        default: empty
      batch_size_entries:
        type: double
        default: empty
