[build]
acl = ["open"]
driver = "$MUTATION_INDEXER/driver.py"
error_log = "$HOME/mutation-indexer-error.log"
jar_dir = "$MUTATION_INDEXER/jars"
manifest_dir = "$HOME/manifests"
output_log = "$HOME/mutation-indexer.log"
pex_file = "$MUTATION_INDEXER/driver-all"
projects = []
spark_submit = "$SPARK_HOME/bin/spark-submit"
study_label = ""

[spark]
master = "yarn"

[spark.app]
name = "gdc_mutation_indexer"

[spark.driver]
max_result_size = "0"
memory = "32g"

[spark.executor]
cores = 12
instances = 24
memory = "24g"

[spark.pyspark]
python = "./mutation-indexer.pex"

[spark.pyspark.driver]
python = "./mutation-indexer.pex"

[spark.sql]
auto_broadcast_join_threshold = -1
case_sensitive = true

[spark.sql.shuffle]
partitions = 1024

[spark.submit]
deploy_mode = "cluster"
