[build]
acl = ["open"]
error_log = "/logs/mutation-indexer-error.log"
jar_dir = "/app/jars"
manifest_dir = "/logs/manifests"
output_log = "/logs/mutation-indexer.log"
projects = []
spark_submit = "$SPARK_HOME/bin/spark-submit"
study_label = ""

[spark]
master = "yarn"
executor_env = {}

[spark.app]
name = "gdc_mutation_indexer"

[spark.driver]
max_result_size = "0"
memory = "32g"

[spark.executor]
cores = 12
instances = 24
memory = "24g"

[spark.pyspark]
python = "uv run --python 3.13"

[spark.pyspark.driver]
python = "uv run --python 3.13"

[spark.sql]
auto_broadcast_join_threshold = -1
case_sensitive = true

[spark.sql.shuffle]
partitions = 1024

[spark.submit]
deploy_mode = "cluster"

[spark.yarn]
app_master_env = {}
