#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Default system properties included when running spark-submit.
# This is useful for setting default environmental settings.

# Example:
# spark.master                     spark://master:7077
# spark.eventLog.enabled           true
# spark.eventLog.dir               hdfs://namenode:8021/directory
# spark.serializer                 org.apache.spark.serializer.KryoSerializer

# Spark settings
spark.executor.cores                4
spark.executor.memory               7g
spark.driver.memory                 6g
spark.yarn.executor.memoryOverhead  512m
spark.yarn.driver.memoryOverhead    512m
spark.executor.extraJavaOptions     -XX:+PrintGCDetails


# Application env variables
spark.yarn.appMasterEnv.SIGNPOST_HOST="172.21.8.206"
spark.yarn.appMasterEnv.S3_HOST="10.64.80.123"
spark.yarn.appMasterEnv.API_HOST="172.21.8.198"

spark.yarn.appMasterEnv.ES_HOST="http://10.64.0.78"
spark.yarn.appMasterEnv.SOURCE_ES_HOST="http://10.64.0.78"
spark.yarn.appMasterEnv.ES_USER=""
spark.yarn.appMasterEnv.ES_PASS=""

# Python settings
spark.yarn.appMasterEnv.PYTHON_EGG_DIR="/tmp"
spark.yarn.appMasterEnv.PYTHON_EGG_CACHE="/tmp"
spark.executorEnv.PYTHON_EGG_DIR="/tmp"
spark.executorEnv.PYTHON_EGG_CACHE="/tmp"

# Cleversafe connection settings
spark.hadoop.fs.s3a.access.key=""
spark.hadoop.fs.s3a.secret.key=""
spark.hadoop.fs.s3a.endpoint=""
spark.hadoop.fs.s3a.proxy.host=""
spark.hadoop.fs.s3a.connection.ssl.enabled=false
spark.hadoop.fs.s3a.proxy.port=80
