[environment]
java_home = ""
spark_home = ""
yarn_conf_dir = ""

[spark]
master = "local[*]"

[spark.app]
name = "gdc_mutation_indexer"

[spark.driver]
max_result_size = "1g"
memory = "12g"

[spark.executor]
cores = 8
instances = 25
memory = "40g"

[spark.pyspark]
python = "./mutation-indexer.pex"
[spark.pyspark.driver]
python = "./mutation-indexer.pex"

[spark.sql]
auto_broadcast_join_threshold = -1
case_sensitive = true
[spark.sql.shuffle]
partitions = 200

[spark.submit]
deploy_mode = "cluster"

[spark.yarn.app_master_env]
pex_python = "python3.9"
pex_root = "/mnt/tmp/.pex"
tmpdir = "/mnt/tmp"

[spark.yarn.executor_env]
pex_python = "python3.9"
pex_root = "/mnt/tmp/.pex"
tmpdir = "/mnt/tmp"

[build]
build_version = "v0"
config_file = "./.configs/test-config.toml"
data_release = "test"
index_types = [
  "CASE_CENTRIC",
  "CNV_CENTRIC",
  "CNV_OCCURRENCE_CENTRIC",
  "GENE_CENTRIC",
  "SSM_CENTRIC",
  "SSM_OCCURRENCE_CENTRIC",
]
jar_dir = "artifacts/jars"
manifest_dir = "./.manifests"
projects = []
study_label = ""

[builders]
[builders.viz.ascat]
is_cached = true
omit_cnv_data = true
[builders.viz.ascat.backup]
mode = "NEITHER"
path = ""

[builders.viz.case]
include_as_arrays = ["project.disease_type", "project.primary_site", "*_ids"]
is_cached = true
repartition_size = 2048
[builders.viz.case.backup]
mode = "NEITHER"
path = ""

[builders.viz.gene_model]
census_file = "s3a://gdc-mutation-indexer/cancer_gene_census_set.tsv.gz"
citobands_file = "s3a://gdc-mutation-indexer/genes.cytobands.tsv.gz"
gene_model_file = "s3a://gdc-mutation-indexer/genes.hg38.v2.json"
is_cached = true
[builders.viz.gene_model.backup]
mode = "NEITHER"
path = ""

[builders.viz.maf_metadata]
is_cached = true
prioritized_experimental_strategies = ["Targeted Sequencing", "WXS"]
[builders.viz.maf_metadata.backup]
mode = "NEITHER"
path = ""

[builders.viz.maf]
is_cached = true
repartition_size = 2048
[builders.viz.maf.backup]
mode = "NEITHER"
path = ""

[builders.viz.primary_aliquot]
is_cached = true
[builders.viz.primary_aliquot.backup]
mode = "NEITHER"
path = ""

[builders.viz.case_centric]
coalesce_size = 12
genes_threshold = 100
include_as_arrays = ["project.disease_type", "project.primary_site"]
is_cached = true
repartition_size = 2048
[builders.viz.case_centric.backup]
mode = "NEITHER"
path = ""

[builders.viz.gene_centric]
coalesce_size = 12
is_cached = true
repartition_size = 2048
[builders.viz.gene_centric.backup]
mode = "NEITHER"
path = ""

[builders.viz.cnv_centric]
coalesce_size = 12
is_cached = true
occurrences_threshold = 100
repartition_size = 2048
[builders.viz.cnv_centric.backup]
mode = "NEITHER"
path = ""

[builders.viz.cnv_occurrence_centric]
coalesce_size = 12
is_cached = true
repartition_size = 2048
[builders.viz.cnv_occurrence_centric.backup]
mode = "NEITHER"
path = ""

[builders.viz.ssm_centric]
coalesce_size = 12
is_cached = true
occurrences_threshold = 100
repartition_size = 2048
[builders.viz.ssm_centric.backup]
mode = "NEITHER"
path = ""

[builders.viz.ssm_occurrence_centric]
coalesce_size = 12
is_cached = true
repartition_size = 2048
[builders.viz.ssm_occurrence_centric.backup]
mode = "NEITHER"
path = ""

[builders.gene_expression.gene_model]
census_file = "s3a://gdc-mutation-indexer/cancer_gene_census_set.tsv.gz"
citobands_file = "s3a://gdc-mutation-indexer/genes.cytobands.tsv.gz"
gene_model_file = "s3a://gdc-mutation-indexer/genes.hg38.v2.json"
is_cached = true
[builders.gene_expression.gene_model.backup]
mode = "NEITHER"
path = ""

[builders.gene_expression.expression_value]
is_cached = true
[builders.gene_expression.expression_value.backup]
mode = "NEITHER"
path = ""

[builders.gene_expression.case]
is_cached = true
[builders.gene_expression.case.backup]
mode = "NEITHER"
path = ""

[builders.gene_expression.primary_aliquot]
is_cached = true
[builders.gene_expression.primary_aliquot.backup]
mode = "NEITHER"
path = ""

[builders.gene_expression.gene_expression]
coalesce_size = 12
is_cached = true
repartition_size = 2048
[builders.gene_expression.gene_expression.backup]
mode = "NEITHER"
path = ""

[aws.s3]
access_key = ""
host = ""
secret_key = ""

[indexd]
host = "indexd.service.consul"
password = ""
port = 80
user = ""

[elasticsearch]
[elasticsearch.connection]
nodes = "http://localhost:9200"
password = ""
use_ssl = false
user = ""
verify_certs = false
[elasticsearch.read]
case_index = "graph_case"
file_index = "graph_file"
[elasticsearch.write]
batch_size_bytes = "16mb"
batch_size_entities = 1000
